apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: teat-application
spec:
  destination:
    namespace: elysium
    server: https://kubernetes.default.svc
  info:
    - name: ""
      value: ""
  project: default
  source:
    path: /
    repoURL: https://github.com/rodrigobiagi/argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace: true