apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-wkr-processador-ap
  namespace: #{namespace}#
spec:
  replicas: #{replicas}#
  selector:
    matchLabels:
      app: wkr-processador-ap
  template:
    metadata:
      labels:
        app: wkr-processador-ap
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: company
                operator: In
                values:
                - tecnobank
      containers:
      - name:  wkr-processador-ap-container
        image: #{image}#:#{imageName}#
        resources:
          requests:
            cpu: #{cpu}#
            memory: #{memory}#
          limits:
            cpu: #{cpu-limits}#
            memory: #{memory-limits}#
        env:
        - name: TZ
          value: America/Sao_Paulo
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-appsettings
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
        - name: config-appsettings
          configMap:
            name: wkr-processador-ap-appsettings
---
apiVersion: v1
kind: Service
metadata:
  name: service-wkr-processador-ap
  namespace: #{namespace}#
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: wkr-processador-ap
---
apiVersion: v1
data:
  tls.crt: #{tlscert}#
  tls.key: #{tlskey}#
kind: Secret
metadata:
  name: tls-tecnobank
  namespace: #{namespace}#
type: kubernetes.io/tls

