apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-backoffice-admin-api
  namespace: #{namespace}#
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-backoffice-admin-api
  minReplicas: #{min-replicas}#
  maxReplicas: #{max-replicas}#
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: #{cpu-average}#
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: #{memory-average}#
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
